const exercises = [
    // Chunk 2
    "Wyciskanie sztangi zza głowy",
    "Wyciskoporzut z hantlami",
    "Wyciskanie gumy oporowej nad głowę",
    "Unoszenie talerza w przód z rotacją",
    "Krążenie ramionami",
    "Wznosy hantli w przód",
    "Wznosy przodem z wyciągu dolnego",
    "Wznosy bokiem na wyciągu dolnym jednorącz",
    "Wznosy hantli bokiem siedząc",
    "Wyciskanie kubańskie siedząc",
    "Wyciskanie hantli jednorącz stojąc",
    "Wznosy przodem na wyciągu dolnym jednorącz",
    "Pompki w staniu na rękach",
    "Wznosy bokiem w opadzie tułowia",
    "Wyciskanie sztangi nad głowę",
    "Wyciskanie nad głowę na maszynie chwytem młotkowym",
    "Pompki szczupak miedzy ławkami",
    "Podciąganie drązka do brody wyciągu dolnego",
    "Wznosy ramion z przeniesieniem w przód",
    "Unoszenie hantli w bok w oparciu o ławke dodatnią",
    "Przyciąganie liny z wyciągu do twarzy z rotacją zewnętrzną",
    "Rotacja kubańska jednorącz stojąc",
    "Przyciąganie liny z wyciągu do twarzy siedząc",
    "Krążenie kettlebell dookoła głowy",
    "Wyciskanie hantli na barki stojąc",
    "Przyciąganie sznura do twarzy leżąc z wyciągu górnego",
    "Full Planche",
    "Rzut piłka o ziemię",
    "Pompki szczupak na krzesłach",
    "Przyciąganie liny z wyciągu do twarzy",
    // Chunk 3
    "Podciąganie sztangi do brody szerokim chwytem",
    "Wyciskanie hantli na barki siedząc",
    "Wyciskanie półsztangi jednorącz stojac",
    "Wyciskanie hantli w klęku jednonóż",
    "Wyciskanie hantli w półklęku",
    "Podciąganie sztangi do brody wąskim chwytem",
    "Wyciskanie nad głowę na maszynie",
    "Skośne skręty tułowia z góry na dół z ciężarem",
    "Podciąganie hantli wzdłuż tułowia",
    "Wznosy bokiem na wyciągu leżąc",
    "Naprzemienne wznosy hantli przód chwytem młotkowym",
    "Kierownica z talerzem",
    "Pompki szczupak",
    "Face pull na kółkach gimnastycznych",
    "Wyciskanie zza głowy na maszynie smitha",
    "Wyciskanie kubańskie stojąc",
    "Podciąganie sztangi do brody",
    "Odwodzenie ramienia jednorącz na maszynie siedząc bokiem",
    "Odwodzenie ramion w tył na bramie",
    "Wymachy ramion",
    "Szerokie wiosłowanie hantlami w opadzie tułowia siedząc",
    "Wznosy bokiem jednorącz w opadzie tułowia na wyciągu dolnym",
    "Unoszenie sztangi w przód",
    "Wyciskanie hantli Arnoldki",
    "Unoszenie ramienia z wykorzystaniem linki wyciągu dolnego",
    "Wznosy bokiem na gumach",
    "Naprzemienne wyciskanie hantli nad głowę stojąc",
    "Wznosy bokiem z półsztangą",
    "Przyciaganie gumy do twarzy",
    // Chunk 4
    "Pompki w staniu na rękach",
    "Naprzemienne wznosy ramion w bok w opadzie tułowia",
    "Wznosy ramienia w bok w oparciu o ławkę dodatnią",
    "Wznosy Y na wyciągu dolnym na ławce dodatniej siedząc",
    "Unoszenie talerza w przód",
    "Wznosy bokiem w opadzie tułowia siedząc",
    "Unoszenie hantli bokiem jednorącz w oparciu o ławkę dodatnią",
    "Wznosy bokiem na linkach",
    "Przyciąganie gumy do brody",
    "Wznosy hantli bokiem",
    "Wznosy hantli do góry",
    "Wznosy Poliquina",
    "Odwodzenie ramion na wyciągu dolnym siedząc na tył barków",
    "Wznosy bokiem zza plecow jednorącz na wyciągu",
    "Podciąganie sztangi do brody na maszynie smitha",
    "Wznosy hantli bokiem jednorącz",
    "Chest Supported Lateral T Raise",
    "Kierownica z hantlem",
    "Wyciskanie kettlebell jednorącz",
    "Wyciskanie półsztangi w półklęku",
    "Wyciskanie hantli na barki siedząc chwytem neutralnym",
    "Wyciskanie półsztangi jednorącz na kolanach",
    "Naprzemienne wznosy hantli w przód",
    "Unoszenie ramienia w leżeniu bokiem z hantlą",
    "Odwodzenie ramienia jednorącz w opadzie z dolnego wyciągu",
    "Pompki szczupak na podwyższeniu nóg",
    "Rozciąganie tyłu naramiennego",
    "Wznosy bokiem na maszynie",
    // Chunk 5
    "Wiosłowanie hantlą szroko w oparciu o ławke",
    "Wyciskanie nad głowę na maszynie smitha",
    "Wznosy “Y” na wyciągu dolnym",
    "Wyciskanie sztangi nad głowę Tsunami",
    "Unoszenie sztangi za plecami",
    "Wyciskanie sztangi nad głowę siedząc",
    "Stanie na rękach"
];

const counts = {};
exercises.forEach(x => { counts[x] = (counts[x] || 0) + 1; });
Object.entries(counts).filter(([k, v]) => v > 1).forEach(([k, v]) => console.log(`${k}: ${v}`));
console.log(`Total items: ${exercises.length}`);
console.log(`Total unique: ${new Set(exercises).size}`);
